### PR TITLE
Basket/RecipeDetail pages

### PR DESCRIPTION
**Pull request by markvinczehu**
- Fixed basket page
- Fixed recipe detail
- done refactorings

### CODE REVIEW

**Review by DanielRailean — CHANGES_REQUESTED** [review]
recipe amount = 0 is needed. It sets the amount back to zero after adding to cart, if you need more you can add then.

**Review by DanielRailean — COMMENTED** [review]
Also , why would you merge master into your branch. Is that conflict?

**Review by DanielRailean — COMMENTED** [review]
Pull request name is also not the best. Fixing and refactoring is not very intuitive :)
Also as you will anyway change the the index, you can make the default value of an item to be 1

**Review by markvinczehu — COMMENTED** [review]
Changed back the uncommencted line

**Comment by markvinczehu** [comment]
> 
> 
> Also , why would you merge master into your branch. Is that conflict?

But on github it says I am merging my branch to master

**Comment by markvinczehu** [comment]
> 
> 
> > Also , why would you merge master into your branch. Is that conflict?
> 
> But on github it says I am merging my branch to master

billede

**Comment by DanielRailean** [comment]
image

**Pull request closed without merging**
